export const TEST_IDS = {
  auth: {
    dashboard: 'auth.dashboard',
    emailInput: 'auth.email-input',
    loginTab: 'auth.login-tab',
    logoutButton: 'auth.logout-button',
    nameInput: 'auth.name-input',
    passwordInput: 'auth.password-input',
    passwordVisibilityButton: 'auth.password-visibility-button',
    registerTab: 'auth.register-tab',
    socialAppleButton: 'auth.social-apple-button',
    socialGoogleButton: 'auth.social-google-button',
    submitButton: 'auth.submit-button',
    userEmail: 'auth.user-email',
  },
  components: {
    catalog: 'components.catalog',
    title: 'components.title',
  },
  details: {
    backButton: 'details.back-button',
    openButton: 'details.open-button',
    screen: 'details.screen',
  },
  onboarding: {
    allergiesNoneButton: 'onboarding.allergies-none-button',
    calculationSexDeclinedButton: 'onboarding.calculation-sex-declined-button',
    confirmPlanButton: 'onboarding.confirm-plan-button',
    confirmProfileButton: 'onboarding.confirm-profile-button',
    currentPainNoButton: 'onboarding.current-pain-no-button',
    doctorRestrictionNoButton: 'onboarding.doctor-restriction-no-button',
    equipmentInput: 'onboarding.equipment-input',
    experienceInput: 'onboarding.experience-input',
    heightInput: 'onboarding.height-input',
    homeButton: 'onboarding.home-button',
    manualStartButton: 'onboarding.manual-start-button',
    nutritionHybridButton: 'onboarding.nutrition-hybrid-button',
    ordinaryDayInput: 'onboarding.ordinary-day-input',
    ordinaryFitnessDoubtNoButton: 'onboarding.ordinary-fitness-doubt-no-button',
    planReviewScreen: 'onboarding.plan-review-screen',
    recompositionButton: 'onboarding.recomposition-button',
    reviewScreen: 'onboarding.review-screen',
    saveDraftButton: 'onboarding.save-draft-button',
    screen: 'onboarding.screen',
    strengthButton: 'onboarding.strength-button',
    supervisedOnlyNoButton: 'onboarding.supervised-only-no-button',
    trainingDaysInput: 'onboarding.training-days-input',
    workoutDurationInput: 'onboarding.workout-duration-input',
    weightInput: 'onboarding.weight-input',
    adultConfirmedButton: 'onboarding.adult-confirmed-button',
    birthYearDeclinedButton: 'onboarding.birth-year-declined-button',
  },
  paywall: {
    empty: 'paywall.empty',
    error: 'paywall.error',
    loading: 'paywall.loading',
    planGroup: 'paywall.plan-group',
    planOption: 'paywall.plan-option',
    profileButton: 'paywall.profile-button',
    purchaseButton: 'paywall.purchase-button',
    redeemOfferCodeButton: 'paywall.redeem-offer-code-button',
    restoreButton: 'paywall.restore-button',
    screen: 'paywall.screen',
  },
  profile: {
    avatarError: 'profile.avatar-error',
    avatarLoadError: 'profile.avatar-load-error',
    avatarNotice: 'profile.avatar-notice',
    avatarPreview: 'profile.avatar-preview',
    avatarReloadButton: 'profile.avatar-reload-button',
    avatarRemoveButton: 'profile.avatar-remove-button',
    avatarUploadButton: 'profile.avatar-upload-button',
    manageSubscriptionButton: 'profile.manage-subscription-button',
    openButton: 'profile.open-button',
    screen: 'profile.screen',
  },
  progress: {
    energyCalendar: 'progress.energy-calendar',
    screen: 'progress.screen',
  },
  screen: {
    backButton: 'screen.back-button',
  },
  tabs: {
    coachTab: 'tabs.coach',
    componentsTab: 'tabs.components',
    diaryTab: 'tabs.diary',
    planTab: 'tabs.plan',
    profileTab: 'tabs.profile',
    progressTab: 'tabs.progress',
    todayTab: 'tabs.today',
  },
  today: {
    energyCard: 'today.energy-card',
    screen: 'today.screen',
  },
} as const;
